apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: dryice-devops
    provider: github
    repository: python-flask-docker
  name: dryice-devops-python-flask-docker
spec:
  description: Imported application for dryice-devops/python-flask-docker
  httpCloneURL: https://github.com/dryice-devops/python-flask-docker.git
  org: dryice-devops
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: python-flask-docker
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/dryice-devops/python-flask-docker.git
